User.create!(name: 'Alice')
User.create!(name: 'Hanako')
User.create!(name: 'Tarou')
User.create!(name: 'Jiro')
User.create!(name: 'Saburo')

Friendship.create!(user_id: 1, friend_id: 2)
Friendship.create!(user_id: 1, friend_id: 3)
Friendship.create!(user_id: 1, friend_id: 4)
Friendship.create!(user_id: 2, friend_id: 1)
Friendship.create!(user_id: 2, friend_id: 5)
Friendship.create!(user_id: 3, friend_id: 1)
Friendship.create!(user_id: 3, friend_id: 2)
Friendship.create!(user_id: 3, friend_id: 4)
Friendship.create!(user_id: 3, friend_id: 5)
Friendship.create!(user_id: 4, friend_id: 1)
Friendship.create!(user_id: 4, friend_id: 3)
Friendship.create!(user_id: 5, friend_id: 1)